fix: add WB 2024 naming convention MQTT topics
wirenboard/conventions pull request #13
Opened 2024-11-18 10:05 UTC by vitalii-wb

Добавил конвенцию названия имен, чтобы можно было ссылаться

2024-11-18 10:11 UTC, sikmir commented on README.md
> +Each MQTT topic has some metadata.
Не совсем корректно, метадата публикуется только в топиках .../meta и сабтопики к ней.

2024-12-13 06:45 UTC, KraPete requested changes
Согласен с Николаем

2025-03-03 23:08 UTC, vitalii-wb commented
Учел комментарии выше

2025-03-03 23:09 UTC, vitalii-wb commented on README.md
> +Each MQTT topic has some metadata.
Изменил формулировку про метатопики, плюс добавил примеры что хорошо, что плохо, а что старое

2025-03-04 04:12 UTC, KraPete approved these changes

2025-03-04 08:07 UTC, merged